### ISSUE TITLE
gcc timespec_get build error

### ISSUE THREAD

**Issue by Funmungus** [jtsiomb/c11threads#10]
Description: gcc build error "c11threads.h:__LINE__: error: static declaration of 'timespec_get' follows non-static declaration
 static inline int timespec_get(struct timespec *ts, int base)"
Possible cause:  #7 PTHREAD_MUTEX_TIMED_NP is not available outside of Linux
Specs: gcc version 5.4.0, on Ubuntu 16.04.2 LTS
__STDC_VERSION__ = 201112L

More info:
At the beginning of c11threads.h `PTHREAD_MUTEX_TIMED_NP` is checked, and if not found `timespec_get` will be defined at the bottom of the header.  pthread.h declares the `timespec_get` function, and defines `PTHREAD_MUTEX_TIMED_NP` as an enum value, and not a macro.

**Comment by jtsiomb** [comment]
fixed. rev. a74a66ab0648917d7b2724e8ef4a265db51efe7a

**Comment by Funmungus** [comment]
Great.  Hope it helped the project.
