### ISSUE TITLE
warning: cast to pointer from integer

### ISSUE THREAD

**Issue by drfiemost** [jtsiomb/c11threads#16]
When compiling on MinGW I get these warnings:

```
c11threads.h: In function 'thrd_exit':
c11threads.h:70:15: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   70 |  pthread_exit((void*)(long)res);
      |               ^
c11threads.h: In function 'thrd_join':
c11threads.h:81:15: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   81 |   *res = (int)(long)retval;
      |               ^
```

That's because long is 32 bit on this platform. The ideal solution would be to replace it with intptr_t but it is only (optionally) available since c99.
Maybe using long long when `__MINGW64__` is defined will do.

**Comment by jtsiomb** [comment]
Even the existing attempt to appease the compiler, with the double-cast, seems pointless and ugly. Adding even more cruft just isn't worth it. I'd say better pass that flag to disable the warning.

Leaving this bug report open, just in case I think about it some more and reconsider. But this is probably a won't-fix.

**Comment by horta** [comment]
[Conversion between pointers and integers are implementation-defined](https://wiki.sei.cmu.edu/confluence/display/c/INT36-C.+Converting+a+pointer+to+integer+or+integer+to+pointer)

I should create a pull request.

**Comment by horta** [comment]
Actually, there is no compliant solution for that kind of code:

```
unsigned int *g(void) {
  unsigned int *ptr = 0xdeadbeef;
  /* ... */
  return ptr;
} 
```

I'm thinking about using `_Thread_local` to statically store (per-thread) that integer. The downside is that this is C11, although gnu99 will probably have that implemented long-time ago.

**Comment by horta** [comment]
Musl has a seemingly working solution:

```c
#include <threads.h>
#include <pthread.h>
#include <stdint.h>

_Noreturn void thrd_exit(int result)
{
	__pthread_exit((void*)(intptr_t)result);
}
```

```c
#include <stdint.h>
#include <threads.h>
#include <pthread.h>

int thrd_join(thrd_t t, int *res)
{
        void *pthread_res;
        __pthread_join(t, &pthread_res);
        if (res) *res = (int)(intptr_t)pthread_res;
        return thrd_success;
}
```

The plus side is that `intptr_t` is C99.

**Comment by jtsiomb** [comment]
Yes conversions are implementation defined, but every implementation defines them as "if the bits you put into it fit, you'll get the same bits out of it".

Going through `intptr_t` is the correct choice to silence the compiler.

**Comment by horta** [comment]
Thanks a lot!
