### ISSUE TITLE
Duplicated declaration of timespec_get() on MacOSX

### ISSUE THREAD

**Issue by tmikov** [jtsiomb/c11threads#18]
Got this error:
```
c11threads.h:262:19: error: static declaration of 'timespec_get' follows non-static declaration
static inline int timespec_get(struct timespec *ts, int base)
                  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/usr/include/time.h:199:5: note: previous declaration is here
int timespec_get(struct timespec *ts, int base);
```

Temporarily worked around it by changing:
```c
#if __STDC_VERSION__ < 201112L || defined(C11THREADS_NO_TIMED_MUTEX)
/* TODO take base into account */
static inline int timespec_get(struct timespec *ts, int base)
```
to 
```c
#if __STDC_VERSION__ < 201112L
/* TODO take base into account */
static inline int timespec_get(struct timespec *ts, int base)
```

Didn't really dig to see what the "proper" fix is, but I suspect timespec_get() was added in a new version of the MacOSX SDK?

**Comment by jtsiomb** [comment]
The correct fix is to change this:

    #ifdef __APPLE__
    /* Darwin doesn't implement timed mutexes currently */
    #define C11THREADS_NO_TIMED_MUTEX
    #endif

... to something that defines it on apple systems only when the SDK version is less than the version which introduced timed mutexes.

I don't have access to MacOS X systems any more, but if you can dig up which SDK version that is, and which preprocessor macro can be used to check for it, I'll be glad to make the necessary changes.

**Comment by horta** [comment]
@jtsiomb I think you can close this one =)
