### ISSUE TITLE
C11THREADS_TIMEDLOCK_POLL_INTERVAL not defined

### ISSUE THREAD

**Issue by landretk** [jtsiomb/c11threads#22]
Compiling on MacOS 12.6.1 fails because this value isn't defined.

It appears it was removed here https://github.com/jtsiomb/c11threads/commit/3124713c5e9789283ad025fa7520e11d75257120#diff-9ba368accb8ef5a50e2b84baf275bbf34f8c9789c300c88f18bdbd51a1a805edL35-L36

**Comment by jtsiomb** [comment]
Thanks for reporting it. The missing definition should now be reinstated. Let me know if there's still a problem.
