### ISSUE TITLE
Test failure on FreeBSD

### ISSUE THREAD

**Issue by johnsonjh** [jtsiomb/c11threads#28]
Hello.

This is actually about C11 threads on FreeBSD 13.2, using *native* C11 threads. What I mean is building the test but including *real* "threads.h" instead of "c11threads.h" and linking with "-lstdthreads", *instead* of "-lthr" (which is "-lpthread" on FreeBSD systems).

I'd expect the test to function identically.  It does on (at least) AIX and Linux/glibc and Linux/musl.

The problem is on FreeBSD, using the real system C11 threads library, results in the following failure:

`test.c:249: thrd_sleep(&dur, ((void *)0)): error 0, expected thrd_success`

It all works as expected using the test with c11threads.h.

**Comment by jtsiomb** [comment]
It might be useful to find out what the return value of the failing `thrd_sleep` call is.

**Comment by johnsonjh** [comment]
I'll check today

**Comment by johnsonjh** [comment]
It is returning 0 (thrd_success is 4).

Edit: errno is set to 60 (Operation timed out).

**Comment by jtsiomb** [comment]
looking at the FreeBSD threads.h, it looks like there is no 0 status, they start from 1. I'm suspecting you're miscompiling something, mixing different header file and library. In my implementation 0 is thrd_success.

Edit: musl libc also uses 0 for thrd_success.

**Comment by johnsonjh** [comment]
Thanks, I'll try to investigate further and reopen if need be
