### ISSUE TITLE
PTHREAD_MUTEX_TIMED_NP Isn't available outside of linux.

### ISSUE THREAD

**Issue by MarcusJohnson91** [jtsiomb/c11threads#7]
There isn't a whole lot more to say, tbh.

**Comment by jtsiomb** [comment]
I'll gladly accept patches or pull requests implementing the equivalent operation on other systems.

**Comment by MarcusJohnson91** [comment]
You wanna tell me what that operation is even supposed to do in the first place?

**Comment by jtsiomb** [comment]
See ISO C11 standard (I'm using draft N1570), sections 7.26.4.2 and 7.26.4.4

**Comment by MarcusJohnson91** [comment]
Thank you. I was just reading the general threads.h definition in that standard.

**Comment by MarcusJohnson91** [comment]
I forgot to mention that I filed a bug report with Apple about their lack of timed mutex, hopefully they'll get around to updating their pthreads implementation before Sierra comes out, but I doubt it.

**Comment by jtsiomb** [comment]
Just merged a pull request from github user "twistdroach", which works around missing timed mutexes by trylocking in a polling loop and sleeping of a while. This isn't a prefect solution, and I'm still open to suggestions and pull requests of more robust solutions, but it'll have to work for now, so I'm closing this enchancement request.
