### ISSUE TITLE
Use feature test macro for transparent drop-in

### ISSUE THREAD

**Issue by stv0g** [jtsiomb/c11threads#8]
You might want use the `__STDC_NO_THREADS__` feature test macro inside the header to check if the compiler / libc provides a implementation.

**Comment by jtsiomb** [comment]
Not a bad idea, but is there _any_ libc out there which supports C11 threads to test against?

**Comment by stv0g** [comment]
http://stackoverflow.com/questions/24557728/does-any-c-library-implement-c11-threads-for-gnu-linux

You could try musl. 

The latest glibc at least sets `__STDC_NO_THREADS__` to `1`. Previous versions don't, sigh -.-

**Comment by lucasart** [comment]
But if you use musl with c11 threads, why would you include this c11thread.h file ?

**Comment by stv0g** [comment]
Thats the point of this issue: Only include `c11thread.h` in case your libc does not have C11 thread support.

**Comment by lucasart** [comment]
According to the C11 standard, the correct solution would be for client code to look like this:
```
#ifdef __STDC_NO_THREADS__
    #include "c11threads.h"  // Use home-grown substitute
#else
    # include <threads.h>  // Use standard libc header
#endif
```
No need to change `c11threads.h`.

**Comment by stv0g** [comment]
You are right.

**Comment by gcerretani** [comment]
The correct way to check for C standard library support for threads at compile time should be

```c
#if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 201112L) && !defined(__STDC_NO_THREADS__)
#include <threads.h>
#else
#include "c11threads.h"
#endif
```

A possible solution to automatically use the standard library if available could be to add these lines to c11threads.h, replacing `#include "c11threads.h"` with the current content of the header.

Note that nowadays all distributions are shipped with a version of glibc supporting threads.
